name: Fetch TMDB Movies

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs daily at 6 hrs, 4 times a day
  workflow_dispatch:       # Allow manual trigger

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python fetch_tmdb.py
